server:
  port: 20000
  servlet:
    context-path: /product
spring:
  application:
    name: sc-product
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  devtools:
    livereload:
      port: 35701